### PR TITLE
MRG: update to v0.8.5 & enable `osx` builds

### PR DESCRIPTION
**Pull request by ctb**
Tackling https://github.com/sourmash-bio/sourmash_plugin_branchwater/issues/160

NOTE: This PR uses the same strategy as https://github.com/conda-forge/sourmash-minimal-feedstock/pull/55 and requires [a newer version of the MacOS SDK](https://conda-forge.org/docs/maintainer/knowledge_base.html#requiring-newer-macos-sdks).

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by BastianZim** [comment]
@conda-forge-admin, please rerender

**Comment by BastianZim** [comment]
You still need to rerender so that the conda-forge infrastructure updates the CI files.

**Comment by ctb** [comment]
> You still need to rerender so that the conda-forge infrastructure updates the CI files.

thank you!!

**Comment by ctb** [comment]
@conda-forge-admin, please rerender

**Comment by ctb** [comment]
@conda-forge-admin, please rerender

**Comment by ctb** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
